name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install

    - name: Test with pytest
      env:
          TESTING_SECRET_KEY: "justtesting"
          TESTING_DB_STRING: "sqlite://"

          SECRET_KEY: "justtesting"
          SQLALCHEMY_DATABASE_URI: "sqlite://"
          
          SENTRY_MONITORING: False
      run: |
        pipenv run pytest
